name: customermanagementapp
description: 顧客情報をDBと連携して管理するアプリ

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #moor-packages
  moor: 3.0.2
  moor_ffi: 0.5.0
  path_provider:
  path:

  #Toast-package
  toast: ^0.1.5

  #Intl-package
  intl: ^0.16.1

  #datetime_picker-package
  flutter_datetime_picker: ^1.3.5

  #color_picker-package
  flutter_colorpicker: ^0.3.2

  #dotted_border-package
  dotted_border:

  #provider-package
  provider: ^4.0.5

  #flutter_picker-package
  flutter_picker: ^1.1.5

  #time-package
  time: ^1.3.0

  #pie_chart-package
  pie_chart: ^3.1.1

  #fl_chart-package
  fl_chart: ^0.9.4

  #custom_switch-package
  custom_switch: ^0.0.1

  #mock_data-package
  mock_data: ^1.2.6

  #shared_preferences-package
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #moor-packages
  moor_generator: 3.0.0
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/flutter_logo.png

  fonts:
    - family: lanobe
      fonts:
        - asset: assets/fonts/lanobe_pop.otf
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
